# Generated by Django 3.1.3 on 2020-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WTNG', 'Waiting'), ('OPEN', 'Opened'), ('RSPD', 'Responded'), ('NATN', 'Needs Attention'), ('CLSD', 'Closed')], default='NEW', max_length=4),
        ),
    ]
