# Generated by Django 3.1.3 on 2020-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(choices=[('P5', 'Parking 5'), ('P4', 'Parking 4'), ('P3', 'Parking 3'), ('P2', 'Parking 2'), ('P1', 'Parking 1'), ('GRND', 'Ground'), ('F1', 'Floor 1'), ('F2', 'Floor 2'), ('F3', 'Floor 3'), ('F4', 'Floor 4'), ('F5', 'Floor 5'), ('F6', 'Floor 6'), ('F7', 'Floor 7'), ('F8', 'Floor 8'), ('ROOF', 'Roof')], default='GRND', max_length=4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('1', 'איטום'), ('2', 'אינסטלציה'), ('3', 'אקוסטיקה'), ('4', 'ביטחון'), ('5', 'בטיחות - אש'), ('6', 'בטיחות - אתר'), ('7', 'בינוי'), ('8', 'חשמל'), ('9', 'מיזוג אוויר'), ('10', 'נגישות'), ('11', 'ניקיון'), ('12', 'תאורה'), ('13', 'תקשורת')], max_length=2),
        ),
    ]
