# Generated by Django 3.1.3 on 2020-11-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201109_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contractor'),
        ),
    ]
