# Generated by Django 3.1.3 on 2020-11-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ticket_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='field_of_work',
            field=models.CharField(default='NaN', max_length=50),
        ),
    ]
