# Generated by Django 3.1.3 on 2020-11-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contractor_field_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'Low (7 / 48)'), ('2', 'Normal (4 / 24)'), ('3', 'High (2 / 8)'), ('4', 'Critical (1 / 3)')], default='1', max_length=1),
        ),
    ]
