# Generated by Django 3.1.3 on 2020-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201110_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
