# Generated by Django 3.1.3 on 2020-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201110_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='field_of_work',
            field=models.CharField(choices=[('1', 'איטום'), ('2', 'אינסטלציה'), ('3', 'אקוסטיקה'), ('4', 'ביטחון'), ('5', 'בטיחות - אש'), ('6', 'בטיחות - אתר'), ('7', 'בינוי'), ('8', 'חשמל'), ('9', 'מיזוג אוויר'), ('10', 'נגישות'), ('11', 'ניקיון'), ('12', 'תאורה'), ('13', 'תקשורת')], default='1', max_length=2),
        ),
    ]
