# Generated by Django 3.1.3 on 2020-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_contractor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
