# Generated by Django 3.1.3 on 2020-11-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201112_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='cellphone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='field_of_work',
            field=models.CharField(choices=[('0', 'לא נבחר'), ('1', 'איטום'), ('2', 'אינסטלציה'), ('3', 'אקוסטיקה'), ('4', 'ביטחון'), ('5', 'בטיחות - אש'), ('6', 'בטיחות - אתר'), ('7', 'בינוי'), ('8', 'חשמל'), ('9', 'מיזוג אוויר'), ('10', 'נגישות'), ('11', 'ניקיון'), ('12', 'תאורה'), ('13', 'תקשורת')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
