# Generated by Django 3.1.3 on 2020-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201112_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
